//
// Created by Muzamil on 6/23/20.
//

#ifndef POINTLOCATION_CONSTANTS_H
#define POINTLOCATION_CONSTANTS_H

#define B_SIZE 1
#define CHILD_SIZE (B_SIZE + 1)
#define VAL_SIZE B_SIZE
#define MIN_VAL 2
//#define INFTY DBL_MAX/
#define INFTY 9007199254740992

#endif //POINTLOCATION_CONSTANTS_H
